"""Closed shared material library for The Abbey at World's End.

This is the ONLY place materials are defined (see ART_BIBLE.md). Assets reference
materials strictly by name via :func:`get_material`. Requesting any name outside
:data:`MATERIAL_LIBRARY` raises ``UnknownMaterialError`` — there are no bespoke
one-off materials, ever.

Style: painterly Principled-BSDF colors retuned to the pixel-art baseline ramps
in docs/ART_REFERENCE_ABBEY.md (mid tones). Surface-defining materials sample
the shared tileable 64x64 pixel-texture set in blender/kits/materials/textures/
(generated by generate_textures.py, committed) through an Image Texture node
with 'Closest' interpolation and explicit UV coordinates, so the pixel-art read
survives into Unity. Emissive materials (flame, ember, warm window, sacred
gold) carry a small emission component so night previews read correctly.

Reference-ramp mapping (mid tones):
    mat_warm_wood   timber highlight          mat_dark_wood  timber shadow
    mat_old_stone   stone_warm + tex_stone_blocks (church, cloister, walls)
    mat_ash         paving + tex_paving       (flagstones, cool-grey masonry)
    mat_wet_stone   glass_stained blue        (stained glass, pennant blue, water)
    mat_thatch      roof_terracotta + tex_roof_tiles (all tiled roofs)
    mat_canvas      plaster + tex_plaster_timber (half-timber infill, awnings)
    mat_iron        roof_slate                (ironwork, slate accents)
    mat_warm_window lit-window warm glow      mat_sacred_gold bell_gold (bells,
                                              finials, pennant yellow)
    mat_foliage     grass + tex_grass         mat_dirt  dirt_path + tex_dirt_path
(tex_cliff_soil is generated for the diorama ground tiles; not wired yet.)
"""

from __future__ import annotations

from pathlib import Path

import bpy

__all__ = [
    "MATERIAL_LIBRARY",
    "MATERIAL_NAMES",
    "TEXTURES_DIR",
    "UnknownMaterialError",
    "get_material",
    "is_library_material",
]

TEXTURES_DIR = Path(__file__).resolve().parent.parent / "kits" / "materials" / "textures"


class UnknownMaterialError(ValueError):
    """Raised when a material name outside the closed library is requested."""


def _srgb(r: int, g: int, b: int) -> tuple[float, float, float, float]:
    """Convert 0-255 sRGB values to linear RGBA as expected by Principled BSDF."""

    def chan(c: int) -> float:
        c_f = c / 255.0
        if c_f <= 0.04045:
            return c_f / 12.92
        return ((c_f + 0.055) / 1.055) ** 2.4

    return (chan(r), chan(g), chan(b), 1.0)


def _hex(code: str) -> tuple[float, float, float, float]:
    """'#rrggbb' (exact ramp values from docs/ART_REFERENCE_ABBEY.md) -> linear RGBA."""
    code = code.lstrip("#")
    return _srgb(int(code[0:2], 16), int(code[2:4], 16), int(code[4:6], 16))


# name -> {base_color, roughness, metallic, emission_color?, emission_strength?,
#          texture?}  ('texture' = stem of a PNG in TEXTURES_DIR sampled as the
#          base color with 'Closest' interpolation; base_color stays as the flat
#          viewport/fallback color, tuned to the texture's ramp mid tone).
# The 17 names below are the FULL closed set from ART_BIBLE.md. Do not add names
# here without updating ART_BIBLE.md first.
MATERIAL_LIBRARY: dict[str, dict] = {
    "mat_warm_wood": {
        # timber ramp highlight — pale worked wood against dark beams
        "base_color": _hex("#8a5f3a"),
        "roughness": 0.85,
        "metallic": 0.0,
    },
    "mat_dark_wood": {
        # timber ramp shadow — beams, bracing, doors, stalls, well frame
        "base_color": _hex("#543a24"),
        "roughness": 0.9,
        "metallic": 0.0,
    },
    "mat_old_stone": {
        # stone_warm mid — church nave, cloister, paving edges
        "base_color": _hex("#a89a80"),
        "roughness": 0.95,
        "metallic": 0.0,
        "texture": "tex_stone_blocks",
    },
    "mat_wet_stone": {
        # glass_stained blue — stained glass, pennant blue field, well water
        "base_color": _hex("#4a6fb0"),
        "roughness": 0.3,
        "metallic": 0.0,
    },
    "mat_thatch": {
        # roof_terracotta mid — every tiled roof shows its courses
        "base_color": _hex("#b5532e"),
        "roughness": 0.9,
        "metallic": 0.0,
        "texture": "tex_roof_tiles",
    },
    "mat_canvas": {
        # plaster mid — half-timber infill, market awnings, sacks, sails
        "base_color": _hex("#e8d9b8"),
        "roughness": 0.9,
        "metallic": 0.0,
        "texture": "tex_plaster_timber",
    },
    "mat_iron": {
        # roof_slate mid — ironwork and slate accents share the cool ramp
        "base_color": _hex("#6b6a78"),
        "roughness": 0.55,
        "metallic": 0.5,
    },
    "mat_warm_window": {
        # lit-window warm glow (reference night note: #e8c063)
        "base_color": _hex("#e8c063"),
        "roughness": 0.4,
        "metallic": 0.0,
        "emission_color": _hex("#e8c063"),
        "emission_strength": 3.0,
    },
    "mat_sacred_gold": {
        # bell_gold mid — bells, finials, pennant yellow
        "base_color": _hex("#e8b83a"),
        "roughness": 0.35,
        "metallic": 0.9,
        "emission_color": _hex("#e8b83a"),
        "emission_strength": 0.15,
    },
    "mat_bone": {
        "base_color": _srgb(226, 218, 196),
        "roughness": 0.7,
        "metallic": 0.0,
    },
    "mat_snow": {
        "base_color": _srgb(235, 240, 245),
        "roughness": 0.8,
        "metallic": 0.0,
    },
    "mat_ash": {
        # paving mid — flagstone plazas and cool-grey masonry (bell tower base)
        "base_color": _hex("#918c80"),
        "roughness": 0.95,
        "metallic": 0.0,
        "texture": "tex_paving",
    },
    "mat_nightmare_black": {
        "base_color": _srgb(12, 10, 16),
        "roughness": 0.9,
        "metallic": 0.0,
    },
    "mat_flame": {
        "base_color": _srgb(255, 147, 41),
        "roughness": 0.5,
        "metallic": 0.0,
        "emission_color": _srgb(255, 128, 32),
        "emission_strength": 8.0,
    },
    "mat_ember": {
        "base_color": _srgb(216, 74, 32),
        "roughness": 0.8,
        "metallic": 0.0,
        "emission_color": _srgb(255, 64, 16),
        "emission_strength": 4.0,
    },
    "mat_foliage": {
        # grass mid — ground grass, canopies, crop leaves
        "base_color": _hex("#5f9430"),
        "roughness": 0.9,
        "metallic": 0.0,
        "texture": "tex_grass",
    },
    "mat_dirt": {
        # dirt_path mid — roads, field soil rows
        "base_color": _hex("#b3925f"),
        "roughness": 1.0,
        "metallic": 0.0,
        "texture": "tex_dirt_path",
    },
}

MATERIAL_NAMES: frozenset[str] = frozenset(MATERIAL_LIBRARY.keys())

assert len(MATERIAL_LIBRARY) == 17, "ART_BIBLE.md defines exactly 17 materials"


def is_library_material(name: str) -> bool:
    """True if *name* is part of the closed shared material library."""
    return name in MATERIAL_LIBRARY


def _load_texture_image(texture: str) -> bpy.types.Image:
    """Load (or reuse) the shared pixel texture <texture>.png from TEXTURES_DIR."""
    image_name = f"{texture}.png"
    image = bpy.data.images.get(image_name)
    if image is not None:
        return image
    path = TEXTURES_DIR / image_name
    if not path.is_file():
        raise FileNotFoundError(
            f"Shared texture {path} is missing. Run "
            "'python3 blender/scripts/generate_textures.py' to regenerate the "
            "committed texture set."
        )
    image = bpy.data.images.load(str(path))
    image.name = image_name
    return image


def _wire_texture(mat: bpy.types.Material, bsdf: bpy.types.ShaderNode, texture: str) -> None:
    """UV -> Image Texture ('Closest', repeat) -> Base Color."""
    tree = mat.node_tree
    tex_node = tree.nodes.new("ShaderNodeTexImage")
    tex_node.name = tex_node.label = texture
    tex_node.image = _load_texture_image(texture)
    tex_node.interpolation = "Closest"  # nearest-neighbor: pixel-art read survives
    tex_node.extension = "REPEAT"
    tex_node.location = (bsdf.location.x - 340, bsdf.location.y)

    uv_node = tree.nodes.new("ShaderNodeTexCoord")
    uv_node.location = (tex_node.location.x - 220, tex_node.location.y)

    tree.links.new(uv_node.outputs["UV"], tex_node.inputs["Vector"])
    tree.links.new(tex_node.outputs["Color"], bsdf.inputs["Base Color"])


def get_material(name: str) -> bpy.types.Material:
    """Create-or-return the shared material *name*.

    Raises :class:`UnknownMaterialError` for any name outside the closed library.
    """
    if name not in MATERIAL_LIBRARY:
        raise UnknownMaterialError(
            f"Material '{name}' is not in the closed library. "
            f"Allowed: {sorted(MATERIAL_LIBRARY)}. "
            "Update ART_BIBLE.md before adding materials."
        )

    existing = bpy.data.materials.get(name)
    if existing is not None:
        return existing

    props = MATERIAL_LIBRARY[name]
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True

    bsdf = None
    for node in mat.node_tree.nodes:
        if node.type == "BSDF_PRINCIPLED":
            bsdf = node
            break
    if bsdf is None:  # pragma: no cover - factory node tree always has one
        bsdf = mat.node_tree.nodes.new("ShaderNodeBsdfPrincipled")
        output = mat.node_tree.nodes.get("Material Output")
        mat.node_tree.links.new(bsdf.outputs["BSDF"], output.inputs["Surface"])

    bsdf.inputs["Base Color"].default_value = props["base_color"]
    bsdf.inputs["Roughness"].default_value = props["roughness"]
    bsdf.inputs["Metallic"].default_value = props["metallic"]
    if "emission_color" in props:
        bsdf.inputs["Emission Color"].default_value = props["emission_color"]
        bsdf.inputs["Emission Strength"].default_value = props["emission_strength"]
    if "texture" in props:
        _wire_texture(mat, bsdf, props["texture"])

    # Flat viewport color as well, so solid-shaded screenshots still read.
    mat.diffuse_color = props["base_color"]
    return mat
