using System;
using System.IO;
using Abbey.Beast;
using Abbey.Buildings;
using Abbey.CameraRig;
using Abbey.Combat;
using Abbey.Core;
using Abbey.Debugging;
using Abbey.Economy;
using Abbey.Hero;
using Abbey.Light;
using Abbey.Nightmares;
using Abbey.Reports;
using Abbey.Sanity;
using Abbey.Session;
using Abbey.Settlement;
using Abbey.UI;
using Abbey.Villagers;
using Abbey.World;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace Abbey.EditorTools
{
    /// <summary>
    /// Builds and saves the Prototype scene entirely from code (AGENTS.md: scenes
    /// are generated by editor bootstrap code and are never the source of truth for
    /// logic). Layout follows docs/VERTICAL_SLICE_SPEC.md §2: shipwreck beach SW,
    /// ruined abbey hill NE (bell tower + chained hound), meadow camp center
    /// (campfire + storage), forest edge NW, a stream.
    ///
    /// P2-10 (final integration) fills the greybox into the FULL Phase 2 slice —
    /// wiring every system earlier tasks were forbidden from touching this file for:
    /// the salvage economy (SalvageSites on the wreck, a StoragePile that raises
    /// capacity, wreck-crate starting stock), villager jobs (Woodcutter/Guard
    /// JobWorkPoints and a JobAssigner applying the default roster), the four abbey
    /// RestorationNodes, the sacred abbey flame, the MorningReport system+panel, the
    /// GameSession win/loss authority with the FirstWhiteNightScenario arming the
    /// White Night on the director, the drowned-sailor shipwreck anchor, and the
    /// debug panels F2–F6 alongside the existing F1 overlay. Runtime systems never
    /// depend on the scene file (PlayMode tests build their own world), so this only
    /// assembles and cross-references components.
    ///
    /// Where a third-party prototype replacement exists under Assets/ThirdParty, it
    /// is preferred. Otherwise, where a generated Blender GLB is already imported
    /// under Assets/Generated/BlenderAssets it is instantiated; otherwise the
    /// builder degrades to primitives. The menu item never fails hard on missing art,
    /// and gameplay never blocks on it.
    /// </summary>
    public static class PrototypeSceneBuilder
    {
        public const string ScenePath = "Assets/_Game/Scenes/Prototype01.unity";
        public const string GeneratedAssetFolder = "Assets/Generated/BlenderAssets";
        public const string ThirdPartyAssetFolder = "Assets/ThirdParty";

        // Landmark positions (map layout, not balance — the map is authored here).
        static readonly Vector3 CampCenter = Vector3.zero;
        static readonly Vector3 BeachCenter = new Vector3(-30f, 0f, -30f);
        static readonly Vector3 AbbeyHillCenter = new Vector3(28f, 0f, 28f);
        static readonly Vector3 ForestEdgeCenter = new Vector3(-28f, 0f, 28f);
        static readonly Vector3 FarVillagerPost = new Vector3(-30f, 0f, 30f);

        [MenuItem("Tools/Abbey/Build Prototype Scene")]
        public static void BuildPrototypeScene()
        {
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
            PopulateScene();

            try
            {
                string dir = Path.GetDirectoryName(Path.GetFullPath(
                    Path.Combine(Application.dataPath, "..", ScenePath)));
                if (!string.IsNullOrEmpty(dir))
                {
                    Directory.CreateDirectory(dir);
                }
                if (EditorSceneManager.SaveScene(scene, ScenePath))
                {
                    Debug.Log($"[Abbey] Prototype greybox scene built and saved to {ScenePath}.");
                }
                else
                {
                    Debug.LogWarning("[Abbey] Scene populated but SaveScene failed; " +
                                     "the open scene is still fully usable (press Play).");
                }
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[Abbey] Scene populated but saving threw: {e.Message}. " +
                                 "The open scene is still fully usable (press Play).");
            }
        }

        /// <summary>Creates every world object in the active scene and wires the full slice.</summary>
        public static void PopulateScene()
        {
            var config = PrototypeConfig.LoadOrDefault();

            BuildGroundAndSun();
            var director = BuildSimulationCore(config);
            var hero = BuildHero();
            BuildCamera(config, hero.transform);
            BuildCamp(config);
            BuildSeedSlots();
            var abbeyFlame = BuildAbbeyHill(config);
            var wreckAnchor = BuildBeach();
            director.shipwreckAnchor = wreckAnchor;
            BuildForestEdgeAndStream();
            BuildVillagers();
            BuildJobsAndEconomy();
            BuildStarterProduction();
            BuildRestorationNodes();
            BuildSessionReportsAndPanels(hero, director, abbeyFlame);
        }

        // ------------------------------------------------------------------
        // World chunks
        // ------------------------------------------------------------------

        static void BuildGroundAndSun()
        {
            // Coastal meadow placeholder, 100x100 units.
            var ground = GameObject.CreatePrimitive(PrimitiveType.Plane);
            ground.name = "Ground";
            ground.transform.localScale = new Vector3(10f, 1f, 10f);

            // Fixed sun matching the camera-relative light rule in ART_BIBLE.md.
            var sunGO = new GameObject("Sun");
            var sun = sunGO.AddComponent<UnityEngine.Light>();
            sun.type = LightType.Directional;
            sunGO.transform.rotation = Quaternion.Euler(50f, IsoCameraController.Yaw - 30f, 0f);
        }

        static NightmareDirector BuildSimulationCore(PrototypeConfig config)
        {
            var clockGO = new GameObject("GameClock");
            clockGO.AddComponent<GameClock>();

            // Seasonal calendar + weather (P3-01). SeasonSystem scales the clock's
            // night phase toward Winter; WeatherSystem pushes the light/bell
            // effectiveness multipliers into DarknessEvaluator and the Bellkeeper.
            // Both observe the clock via EventBus and read SeasonConfig — no wiring.
            var worldGO = new GameObject("WorldSystems");
            worldGO.AddComponent<SeasonSystem>();
            worldGO.AddComponent<WeatherSystem>();

            // Seed-slot settlement growth (P3-02). Authored slots are added later
            // (BuildSeedSlots, once the camp lights exist so the hug rule can read
            // lit ground); completing a building opens child slots beside it.
            worldGO.AddComponent<SeedSlotSystem>();

            // Sanity / dread / asylum (P3-03). Tracks each villager's persistent
            // sanity track, turns dark-exposure into dread and insanity, drives asylum
            // admission and the home-recovery dread spill. Observes the clock via
            // EventBus and reads SanityConfig — no wiring; it auto-finds the AsylumZone.
            worldGO.AddComponent<SanitySystem>();

            // Light-band combat + two-tier settler home defense (P3-05). Each night
            // HomeDefenseSystem keeps occupied destructible homes asleep until a
            // monster reaches the door, then flares the interior light and fires from
            // lit windows at a sanity cost; overwhelmed homes are razed. Reads
            // CombatConfig and the SanitySystem shelter map — no wiring.
            worldGO.AddComponent<HomeDefenseSystem>();

            // Night escalation + nightly dark objective (P3-06). Turns the night index
            // + season into a wave budget for the director and generates one dark
            // objective per night that only a warrior/hero/beast can solve. Reads the
            // CombatConfig escalation section — no wiring. Only drives the wave when
            // PrototypeConfig.phase3NightsEnabled is on (off by default).
            worldGO.AddComponent<NightEscalationSystem>();

            // Hound evolution (P3-07). Each dawn it scores the five paths (Guardian /
            // War / Starved / Sacred / Broken) from the hound's accumulated treatment
            // history + bond averages + Hound doctrine, adopts/locks the dominant path
            // and pushes its behaviour onto the HoundController, exposing a beast-status
            // value for P3-10 pressures and the P3-14 end summary. Reads
            // HoundEvolutionConfig; auto-finds the hound — no wiring.
            worldGO.AddComponent<HoundEvolutionSystem>();

            // Villagers register with the static DuskRecallSystem in OnEnable —
            // no scene object needed for it.

            var directorGO = new GameObject("NightmareDirector");
            directorGO.transform.position = CampCenter; // spawn ring measured from camp
            var director = directorGO.AddComponent<NightmareDirector>();

            var debugGO = new GameObject("DebugOverlay");
            debugGO.AddComponent<DebugOverlay>();
            debugGO.AddComponent<LightZoneGizmos>();

            return director;
        }

        static GameObject BuildHero()
        {
            // bellkeeper_lowpoly GLB when imported (center-bottom pivot), else a capsule.
            var hero = InstantiateGenerated("bellkeeper_lowpoly", new Vector3(2f, 0f, -2f),
                "Bellkeeper", PrimitiveType.Capsule, Vector3.one, 1f);
            var controller = hero.AddComponent<BellkeeperController>();
            controller.useDirectInput = true;
            hero.AddComponent<BellkeeperInputBindings>();
            return hero;
        }

        static void BuildCamera(PrototypeConfig config, Transform followTarget)
        {
            var camGO = new GameObject("IsoCamera");
            camGO.tag = "MainCamera";
            var cam = camGO.AddComponent<Camera>();
            cam.orthographic = true;
            cam.orthographicSize = config.cameraDefaultOrthoSize;
            camGO.transform.rotation = Quaternion.Euler(
                IsoCameraController.Pitch, IsoCameraController.Yaw, 0f);
            var rig = camGO.AddComponent<IsoCameraController>();
            rig.SetWorldBounds(new Vector2(-50f, -50f), new Vector2(50f, 50f));
            rig.FocusOn(CampCenter);
            rig.SetFollowTarget(followTarget);
        }

        static void BuildCamp(PrototypeConfig config)
        {
            // Campfire: the first light zone. GLB when imported, cylinder otherwise.
            var campfire = InstantiateGenerated("campfire_t1", CampCenter, "Campfire",
                PrimitiveType.Cylinder, new Vector3(0.8f, 0.25f, 0.8f), 0.25f);
            var fireLight = campfire.AddComponent<LightSource>();
            fireLight.radius = config.campfireRadius;
            fireLight.strength = config.campfireStrength;
            fireLight.fuelSeconds = config.defaultFuelSeconds;
            fireLight.fuelConsumptionPerSecond = config.fuelConsumptionPerSecond;

            // Storage pile: raises the ledger's capacity (StoragePile registers in
            // OnEnable). The wreck-crate starting stock is granted at play-start by
            // SettlementEconomyBootstrap, once this pile's capacity is counted.
            var storage = InstantiateGenerated("storage_pile_t1", new Vector3(3f, 0f, 3f),
                "StoragePile", PrimitiveType.Cube, new Vector3(1.2f, 0.6f, 1.2f), 0.3f);
            storage.AddComponent<StoragePile>();

            // Shelters are destructible homes (P3-05): they carry a Building bound to
            // the shelter_t1 catalog entry so HomeDefenseSystem can wake, flare and
            // (if overwhelmed) raze them. Occupants are assigned at play-start by the
            // SettlerHomeBootstrap through the SanitySystem shelter map.
            MakeHome(new Vector3(-4f, 0f, 2f), "Shelter_A");
            MakeHome(new Vector3(-2f, 0f, 5f), "Shelter_B");

            // Lantern post on the camp's dark side, toward the abbey path.
            var lantern = InstantiateGenerated("lantern_post_t1", new Vector3(10f, 0f, 6f),
                "LanternPost", PrimitiveType.Cube, new Vector3(0.3f, 2f, 0.3f), 1f);
            var lanternLight = lantern.AddComponent<LightSource>();
            lanternLight.radius = config.lanternRadius;
            lanternLight.strength = config.lanternStrength;
            lanternLight.fuelSeconds = config.defaultFuelSeconds;
            lanternLight.fuelConsumptionPerSecond = config.fuelConsumptionPerSecond;

            // Warrior tier (P3-06): a lodge on the dark edge of camp promotes settlers
            // into Dark-capable warriors (recruit via the F6 combat panel / debug tools)
            // and a watchtower gives ranged support + the vision that arms the nightly
            // dark objective. Both carry a Building bound to their catalog entry so the
            // WarriorStructure component (attached by Building.Construct) drives them.
            MakeWarriorStructure("warrior_lodge_t1", new Vector3(-8f, 0f, 6f), "WarriorLodge",
                WarriorStructureRole.Lodge, new Vector3(3f, 2.5f, 3f), 1.25f);
            MakeWarriorStructure("watchtower_t1", new Vector3(8f, 0f, -4f), "Watchtower",
                WarriorStructureRole.Watchtower, new Vector3(1.6f, 3.5f, 1.6f), 1.75f);
        }

        /// <summary>
        /// A warrior structure (P3-06): the catalog visual plus a Building bound to the
        /// entry and the matching <see cref="WarriorStructure"/> role. Mirrors
        /// <see cref="MakeHome"/> (no Building.Construct, so no build-time side effects).
        /// </summary>
        static void MakeWarriorStructure(string id, Vector3 groundPos, string name,
            WarriorStructureRole role, Vector3 placeholderScale, float placeholderYOffset)
        {
            var go = InstantiateGenerated(id, groundPos, name,
                PrimitiveType.Cube, placeholderScale, placeholderYOffset);
            var building = go.AddComponent<Building>();
            var type = BuildingCatalog.LoadOrDefault().Find(id);
            if (type != null)
            {
                building.Initialize(type);
            }
            var structure = go.AddComponent<WarriorStructure>();
            structure.role = role;
        }

        /// <summary>
        /// Authors the initial seed-slot set (P3-02) once the camp lights stand, so
        /// the hug rule sees lit ground. Slots ring the camp — beside the shelters
        /// and along the lit path toward the abbey — as the open plots the player
        /// grows from. Completing a building on any of them opens child slots beside
        /// it. The system itself was created in BuildSimulationCore.
        /// </summary>
        static void BuildSeedSlots()
        {
            var system = UnityEngine.Object.FindFirstObjectByType<SeedSlotSystem>();
            if (system == null)
            {
                return;
            }

            // Open plots hugging the camp fire/shelters and the lantern-lit path.
            system.AddAuthoredSlot(new Vector3(-6f, 0f, 2f), SlotSizeClass.Medium);
            system.AddAuthoredSlot(new Vector3(-4f, 0f, 5f), SlotSizeClass.Medium);
            system.AddAuthoredSlot(new Vector3(4f, 0f, -3f), SlotSizeClass.Small);
            system.AddAuthoredSlot(new Vector3(6f, 0f, 3f), SlotSizeClass.Large);
            // A locked plot further out: only reachable once growth/light reaches it.
            system.AddAuthoredSlot(new Vector3(12f, 0f, 8f), SlotSizeClass.Medium,
                SlotState.Locked);
        }

        /// <summary>
        /// The shipwreck: hull, crates, and two <see cref="SalvageSite"/> nodes the
        /// Salvager villagers deplete into the ledger (VERTICAL_SLICE_SPEC §3). The
        /// hull doubles as the drowned-sailor shipwreck anchor (returned so the
        /// director's water-death gate has a location).
        /// </summary>
        static Transform BuildBeach()
        {
            var hull = InstantiateGenerated("shipwreck_hull", BeachCenter, "ShipwreckHull",
                PrimitiveType.Cube, new Vector3(8f, 2.5f, 3f), 1.25f);
            InstantiateGenerated("shipwreck_crate_closed", BeachCenter + new Vector3(4f, 0f, 2f),
                "WreckCrate_A", PrimitiveType.Cube, new Vector3(1f, 1f, 1f), 0.5f);
            InstantiateGenerated("shipwreck_crate_closed", BeachCenter + new Vector3(5.5f, 0f, 0.5f),
                "WreckCrate_B", PrimitiveType.Cube, new Vector3(1f, 1f, 1f), 0.5f);
            InstantiateGenerated("shipwreck_barrel", BeachCenter + new Vector3(2f, 0f, 4f),
                "WreckBarrel", PrimitiveType.Cylinder, new Vector3(0.5f, 0.5f, 0.5f), 0.5f);

            // Two finite salvage nodes on the wreck (pool sizes come from EconomyConfig).
            CreateSalvageSite("SalvageSite_A", BeachCenter + new Vector3(4f, 0f, 2f));
            CreateSalvageSite("SalvageSite_B", BeachCenter + new Vector3(2f, 0f, 4f));

            return hull.transform;
        }

        static void CreateSalvageSite(string name, Vector3 groundPos)
        {
            var go = new GameObject(name);
            go.transform.position = groundPos;
            go.AddComponent<SalvageSite>();
        }

        static LightSource BuildAbbeyHill(PrototypeConfig config)
        {
            // Low greybox hill so the abbey reads as "up".
            var hill = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
            hill.name = "AbbeyHill";
            hill.transform.position = AbbeyHillCenter + new Vector3(0f, 0.25f, 0f);
            hill.transform.localScale = new Vector3(12f, 0.25f, 12f);
            float hillTop = 0.5f;

            var towerPos = AbbeyHillCenter + new Vector3(0f, hillTop, 0f);
            InstantiateGenerated("bell_tower_ruined", towerPos, "BellTower",
                PrimitiveType.Cube, new Vector3(3f, 6f, 3f), 3f);
            InstantiateGenerated("abbey_wall_broken", towerPos + new Vector3(-4f, 0f, 1f),
                "AbbeyWall_A", PrimitiveType.Cube, new Vector3(4f, 1.5f, 0.5f), 0.75f);
            InstantiateGenerated("abbey_wall_broken", towerPos + new Vector3(1f, 0f, -4f),
                "AbbeyWall_B", PrimitiveType.Cube, new Vector3(0.5f, 1.5f, 4f), 0.75f);

            // Sacred abbey flame: win/loss anchor and the hound's home light.
            var flameGO = new GameObject("AbbeyFlame");
            flameGO.transform.position = towerPos + new Vector3(1.5f, 0f, 1.5f);
            var flame = flameGO.AddComponent<LightSource>();
            flame.radius = config.sacredFlameRadius;
            flame.strength = config.sacredFlameStrength;
            flame.sacred = true;
            flame.fuelSeconds = -1f; // 0.1: the sacred flame does not burn out

            // The chained Black Hound at the tower base.
            var chainPos = towerPos + new Vector3(2f, 0f, -1.5f);
            InstantiateGenerated("hound_chain", chainPos, "HoundChain",
                PrimitiveType.Cylinder, new Vector3(0.3f, 0.1f, 0.3f), 0.1f);
            var hound = InstantiateGenerated("black_hound_lowpoly",
                chainPos + new Vector3(0.8f, 0f, 0f), "BlackHound",
                PrimitiveType.Capsule, new Vector3(1.2f, 0.9f, 1.2f), 0.9f);
            hound.AddComponent<HoundController>();

            return flame;
        }

        static void BuildForestEdgeAndStream()
        {
            for (int i = 0; i < 5; i++)
            {
                var offset = new Vector3((i % 3) * 4f - 4f, 0f, (i / 3) * 5f);
                InstantiateGenerated("forest_tree_01", ForestEdgeCenter + offset,
                    $"ForestTree_{i}", PrimitiveType.Cylinder,
                    new Vector3(0.5f, 3f, 0.5f), 3f);
            }
            InstantiateGenerated("rock_cluster_01", ForestEdgeCenter + new Vector3(6f, 0f, -3f),
                "RockCluster", PrimitiveType.Sphere, new Vector3(1.5f, 1f, 1.5f), 0.4f);

            // Stream: a flat blue strip running along the forest edge toward the sea.
            var stream = GameObject.CreatePrimitive(PrimitiveType.Cube);
            stream.name = "Stream";
            stream.transform.position = new Vector3(-15f, 0.02f, 18f);
            stream.transform.localScale = new Vector3(45f, 0.05f, 2.5f);
            stream.transform.rotation = Quaternion.Euler(0f, -20f, 0f);
            var renderer = stream.GetComponent<Renderer>();
            if (renderer != null && renderer.sharedMaterial != null)
            {
                var mat = new Material(renderer.sharedMaterial) { color = new Color(0.25f, 0.45f, 0.7f) };
                renderer.sharedMaterial = mat;
            }
        }

        static void BuildVillagers()
        {
            // 11 villagers around camp; positions fan out inside/near the fire.
            for (int i = 0; i < 11; i++)
            {
                float angle = i / 11f * Mathf.PI * 2f;
                float ringRadius = 3f + (i % 3);
                var pos = CampCenter + new Vector3(
                    Mathf.Cos(angle) * ringRadius, 0f, Mathf.Sin(angle) * ringRadius);
                CreateVillager($"Villager_{i:D2}", pos, seed: i);
            }

            // The 12th villager works the far forest edge: the dusk drama beat.
            CreateVillager("Villager_FarNW", FarVillagerPost, seed: 11);
        }

        /// <summary>
        /// A destructible-home shelter: the shelter_t1 visual plus a Building bound to
        /// the catalog entry so P3-05 home defense (wake / flare / raze) drives it.
        /// </summary>
        static void MakeHome(Vector3 groundPos, string name)
        {
            var go = InstantiateGenerated("shelter_t1", groundPos, name,
                PrimitiveType.Cube, new Vector3(2f, 1.5f, 2f), 0.75f);
            var building = go.AddComponent<Building>();
            var type = BuildingCatalog.LoadOrDefault().Find("shelter_t1");
            if (type != null)
            {
                building.Initialize(type);
            }
        }

        static void CreateVillager(string name, Vector3 groundPos, int seed)
        {
            // villager_lowpoly GLB when imported, else a small capsule.
            var go = InstantiateGenerated("villager_lowpoly", groundPos, name,
                PrimitiveType.Capsule, new Vector3(0.6f, 0.9f, 0.6f), 0.9f);
            var agent = go.AddComponent<VillagerAgent>();
            agent.seed = seed;
        }

        // ------------------------------------------------------------------
        // Phase 2 jobs + economy
        // ------------------------------------------------------------------

        /// <summary>
        /// The Phase 2 logistics layer (replaces the 0.1 VillagerWorkAssigner):
        /// Woodcutter JobWorkPoints at the forest edge, Guard JobWorkPoints in camp,
        /// a <see cref="JobAssigner"/> that applies the data-driven default roster to
        /// the registered villagers on Start, and the <see cref="SettlementEconomyBootstrap"/>
        /// that grants the wreck-crate starting stock once storage capacity exists.
        /// Salvagers find the wreck <see cref="SalvageSite"/>s, Builders serve the
        /// abbey <see cref="RestorationNode"/>s, Tenders feed the lights — all via
        /// the registries those systems already keep, no wiring needed here.
        /// </summary>
        static void BuildJobsAndEconomy()
        {
            // Woodcutter stands at the forest edge (near the tree cluster).
            CreateJobWorkPoint("WoodcutterPoint_A", VillagerJob.Woodcutter,
                ForestEdgeCenter + new Vector3(0f, 0f, 2f));
            CreateJobWorkPoint("WoodcutterPoint_B", VillagerJob.Woodcutter,
                ForestEdgeCenter + new Vector3(3f, 0f, -1f));

            // Guard posts on the camp's dark side, toward the abbey path.
            CreateJobWorkPoint("GuardPost_East", VillagerJob.Guard, new Vector3(9f, 0f, 4f));
            CreateJobWorkPoint("GuardPost_South", VillagerJob.Guard, new Vector3(2f, 0f, -8f));

            var jobsGO = new GameObject("JobAssigner");
            jobsGO.AddComponent<JobAssigner>();

            var econGO = new GameObject("EconomyBootstrap");
            econGO.AddComponent<SettlementEconomyBootstrap>();

            // Assign settlers to the destructible-home shelters (P3-05 occupancy) via
            // the SanitySystem shelter map, so homes have someone to defend and lose.
            var homeGO = new GameObject("SettlerHomeBootstrap");
            homeGO.AddComponent<SettlerHomeBootstrap>();
        }

        static void CreateJobWorkPoint(string name, VillagerJob job, Vector3 groundPos)
        {
            var go = new GameObject(name);
            go.transform.position = groundPos;
            var point = go.AddComponent<JobWorkPoint>();
            point.job = job;
        }

        /// <summary>
        /// The renewable seasonal economy (P3-04): a starter Grain Field and Charcoal
        /// Kiln standing near camp as completed <see cref="ProductionBuilding"/>s, plus
        /// an authored field seed-slot for the player to raise more. Assign a Farmer /
        /// Charcoaler to them (jobs debug flow) and fast-forward days: the field's grain
        /// ticks up on harvest days and stops in Winter, while the kiln converts wood to
        /// coal year-round. Recipes/yields all live in EconomyConfig. Watch it on the F2
        /// economy panel alongside the F7 season panel.
        /// </summary>
        static void BuildStarterProduction()
        {
            var field = InstantiateGenerated("field_plot_t1", new Vector3(-8f, 0f, 4f),
                "GrainField", PrimitiveType.Cube, new Vector3(2f, 0.4f, 2f), 0.2f);
            var fieldProduction = field.AddComponent<ProductionBuilding>();
            fieldProduction.Initialize("field_plot_t1");

            var kiln = InstantiateGenerated("charcoal_kiln_t1", new Vector3(-9f, 0f, 1f),
                "CharcoalKiln", PrimitiveType.Cube, new Vector3(2f, 1.4f, 2f), 0.7f);
            var kilnProduction = kiln.AddComponent<ProductionBuilding>();
            kilnProduction.Initialize("charcoal_kiln_t1");

            // A starter field plot the player can build (seed-slot gated, P3-02).
            var slots = UnityEngine.Object.FindFirstObjectByType<SeedSlotSystem>();
            if (slots != null)
            {
                slots.AddAuthoredSlot(new Vector3(-10f, 0f, 4f), SlotSizeClass.Medium);
            }
        }

        /// <summary>
        /// The four fixed abbey restoration nodes (VERTICAL_SLICE_SPEC §5), pre-placed
        /// as ConstructionSites on the abbey hill via <see cref="RestorationNode.Place"/>.
        /// Builders serve them through the normal ConstructionSite delivery economy.
        /// </summary>
        static void BuildRestorationNodes()
        {
            var basePos = AbbeyHillCenter + new Vector3(0f, 0.5f, 0f);
            RestorationNode.Place(RestorationNodeKind.AbbeyGate,
                basePos + new Vector3(-3f, 0f, -4f));
            RestorationNode.Place(RestorationNodeKind.BellTower,
                basePos + new Vector3(0f, 0f, 0.5f));
            RestorationNode.Place(RestorationNodeKind.CandleShrine,
                basePos + new Vector3(3.5f, 0f, 2f));
            RestorationNode.Place(RestorationNodeKind.AsylumCorner,
                basePos + new Vector3(-3.5f, 0f, 3.5f));
        }

        // ------------------------------------------------------------------
        // Session, reports, and debug panels
        // ------------------------------------------------------------------

        /// <summary>
        /// Wires the run-level systems: the MorningReport system+panel (dawn
        /// consequence report), the GameSession win/loss authority (referencing the
        /// hero and the sacred abbey flame), the FirstWhiteNightScenario (arming the
        /// director for the White Night), the GameOutcome end screen, and the debug
        /// panels F2–F6 alongside the existing F1 DebugOverlay.
        /// </summary>
        static void BuildSessionReportsAndPanels(
            GameObject hero, NightmareDirector director, LightSource abbeyFlame)
        {
            var bellkeeper = hero.GetComponent<BellkeeperController>();

            // Morning consequence report (system + player-facing panel, F5).
            var reportsGO = new GameObject("MorningReportSystem");
            reportsGO.AddComponent<MorningReportSystem>();
            reportsGO.AddComponent<MorningReportPanel>();

            // The scripted climax: arms the director's harder schedule at the dusk
            // before the White Night.
            var scenarioGO = new GameObject("FirstWhiteNightScenario");
            var scenario = scenarioGO.AddComponent<FirstWhiteNightScenario>();
            scenario.director = director;

            // The outcome authority + end screen (F6).
            var sessionGO = new GameObject("GameSession");
            var session = sessionGO.AddComponent<GameSession>();
            session.bellkeeper = bellkeeper;
            session.abbeyFlame = abbeyFlame;
            sessionGO.AddComponent<GameOutcomePanel>();

            // Debug overlays for every hidden system (AGENTS.md): F2 economy, F3
            // buildings, F4 nightmare (F1 DebugOverlay is built in BuildSimulationCore).
            var panelsGO = new GameObject("DebugPanels");
            panelsGO.AddComponent<EconomyDebugPanel>();
            var buildingPanel = panelsGO.AddComponent<BuildingDebugPanel>();
            buildingPanel.placementMarker = hero.transform;
            var nightmarePanel = panelsGO.AddComponent<NightmareDebugPanel>();
            nightmarePanel.director = director;

            // Season/weather overlay (F11). WeatherSystem auto-finds the Bellkeeper,
            // but hand it the reference so the multiplier is pushed from frame one.
            // (F11/F10 here: F7/F8 belong to the player HUD/minimap below, F5 to the
            // morning report.)
            panelsGO.AddComponent<SeasonDebugPanel>();
            var weather = UnityEngine.Object.FindFirstObjectByType<WeatherSystem>();
            if (weather != null)
            {
                weather.bellkeeper = bellkeeper;
            }

            // Seed-slot settlement overlay (F10): slot counts, light debt, slot gizmos.
            panelsGO.AddComponent<SettlementDebugPanel>();

            // Sanity overlay (F9, top-left): per-villager sanity/dread bars, asylum
            // roster, tonight's held units.
            panelsGO.AddComponent<SanityDebugPanel>();

            // Combat + home-defense overlay (F6, right): band multipliers, live
            // monster count, and each destructible home's state + hit-point bar.
            panelsGO.AddComponent<CombatDebugPanel>();

            // Player-facing HUD + minimap (from main). Display-only; F7/F8 toggle them.
            var hudGO = new GameObject("PlayerHud");
            hudGO.AddComponent<GameHud>();
            hudGO.AddComponent<MinimapPanel>();
        }

        // ------------------------------------------------------------------
        // Prototype-art helper
        // ------------------------------------------------------------------

        /// <summary>
        /// Instantiates staged third-party art or the imported GLB for
        /// <paramref name="assetId"/> when either exists, otherwise a primitive
        /// stand-in. Generated GLB pivots are center-bottom (ART_BIBLE.md) so they
        /// sit directly on <paramref name="groundPos"/>; primitives are lifted by
        /// <paramref name="primitiveYOffset"/> because Unity primitives pivot at
        /// their center. Never throws.
        /// </summary>
        static GameObject InstantiateGenerated(
            string assetId, Vector3 groundPos, string name,
            PrimitiveType fallback, Vector3 fallbackScale, float primitiveYOffset)
        {
            var thirdParty = InstantiateThirdPartyReplacement(assetId, groundPos, name);
            if (thirdParty != null)
            {
                return thirdParty;
            }

            try
            {
                string assetPath = $"{GeneratedAssetFolder}/{assetId}.glb";
                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);
                if (prefab != null)
                {
                    var instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab);
                    if (instance != null)
                    {
                        instance.name = name;
                        instance.transform.position = groundPos;
                        return instance;
                    }
                }
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[Abbey] Could not instantiate generated asset " +
                                 $"'{assetId}' ({e.Message}); using a primitive stand-in.");
            }

            var go = GameObject.CreatePrimitive(fallback);
            go.name = name;
            go.transform.position = groundPos + new Vector3(0f, primitiveYOffset, 0f);
            go.transform.localScale = fallbackScale;
            return go;
        }

        static GameObject InstantiateThirdPartyReplacement(
            string assetId, Vector3 groundPos, string name)
        {
            string assetPath = ThirdPartyReplacementPathFor(assetId);
            if (string.IsNullOrEmpty(assetPath))
            {
                return null;
            }

            try
            {
                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);
                if (prefab == null)
                {
                    Debug.LogWarning($"[Abbey] Third-party replacement for " +
                                     $"'{assetId}' was not found at {assetPath}; " +
                                     "trying generated art.");
                    return null;
                }

                var instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab);
                if (instance == null)
                {
                    return null;
                }

                instance.name = name;
                instance.transform.position = groundPos;
                instance.transform.localScale = ThirdPartyReplacementScaleFor(assetId);
                return instance;
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[Abbey] Could not instantiate third-party " +
                                 $"replacement for '{assetId}' ({e.Message}); " +
                                 "trying generated art.");
                return null;
            }
        }

        static string ThirdPartyReplacementPathFor(string assetId)
        {
            switch (assetId)
            {
                case "campfire_t1":
                    return $"{ThirdPartyAssetFolder}/Kenney/NatureKit/FBX/campfire_stones.fbx";
                case "storage_pile_t1":
                    return $"{ThirdPartyAssetFolder}/Kenney/NatureKit/FBX/log_stackLarge.fbx";
                case "shipwreck_hull":
                    return $"{ThirdPartyAssetFolder}/Kenney/NatureKit/FBX/canoe.fbx";
                case "shipwreck_crate_closed":
                    return $"{ThirdPartyAssetFolder}/Quaternius/MedievalVillageMegaKit/FBX/Prop_Crate.fbx";
                case "shipwreck_barrel":
                    return $"{ThirdPartyAssetFolder}/Quaternius/MedievalVillageMegaKit/FBX/Prop_Wagon.fbx";
                case "abbey_wall_broken":
                    return $"{ThirdPartyAssetFolder}/Quaternius/MedievalVillageMegaKit/FBX/Wall_UnevenBrick_Straight.fbx";
                case "forest_tree_01":
                    return $"{ThirdPartyAssetFolder}/Kenney/NatureKit/FBX/tree_pineDefaultA.fbx";
                case "rock_cluster_01":
                    return $"{ThirdPartyAssetFolder}/Kenney/NatureKit/FBX/rock_largeA.fbx";
                case "villager_lowpoly":
                    return $"{ThirdPartyAssetFolder}/Quaternius/UniversalBaseCharacters/BaseCharacters/Unity/Superhero_Male_FullBody.fbx";
                default:
                    return null;
            }
        }

        static Vector3 ThirdPartyReplacementScaleFor(string assetId)
        {
            switch (assetId)
            {
                case "shipwreck_hull":
                    return new Vector3(4f, 4f, 4f);
                case "abbey_wall_broken":
                    return new Vector3(2f, 2f, 2f);
                case "forest_tree_01":
                    return new Vector3(2f, 2f, 2f);
                case "rock_cluster_01":
                    return new Vector3(2f, 2f, 2f);
                default:
                    return Vector3.one;
            }
        }
    }
}
